"""Node functions for the Vizzy LangGraph — Phase 4.

Node responsibilities:
  load_context              — Retrieve conversation history from the database.
  resolve_assets            — Resolve input/target asset metadata.
  understand_intent         — Classify user intent using the LLM.
  generate_image            — TEXT → IMAGE (FLUX.1-schnell).
  transform_image           — IMAGE_TRANSFORMATION (FLUX.1-Kontext-dev, 1 input).
  refine_image              — IMAGE_REFINEMENT (FLUX.1-Kontext-dev, parent lineage).
  transform_multiple_images — MULTI_IMAGE_TRANSFORMATION (composited → FLUX.1-Kontext-dev).
  save_result               — Upload generated bytes, create asset record + relationships.
  save_assistant_message    — Persist the assistant turn and link the asset.
  unsupported_request       — Return an informative error message.

All provider calls happen exclusively in this module.
No HF or Groq SDK imports in routes, services, or repositories.
"""

import logging
import uuid
from typing import Any

from app.ai.context.asset_resolver import AssetResolver
from app.ai.context.builder import ContextBuilder
from app.ai.graph.state import VizzyState
from app.ai.intent.classifier import IntentClassifier
from app.ai.intent.schemas import IntentType
from app.ai.providers.image.huggingface_provider import HuggingFaceImageProvider
from app.core.config import get_settings
from app.core.exceptions import ImageGenerationError, ImageTransformationError, NoTargetImageError
from app.db.repositories.asset import AssetRepository
from app.db.repositories.message import MessageRepository
from app.services.storage_service import StorageService

logger = logging.getLogger(__name__)


# ── Helpers ────────────────────────────────────────────────────────────────────


def _generation_response_text(intent: IntentType | None) -> str:
    """Return a friendly assistant response for the given intent."""
    if intent == IntentType.IMAGE_GENERATION:
        return "Here's the image I generated based on your description."
    if intent == IntentType.IMAGE_TRANSFORMATION:
        return "Here's your transformed image."
    if intent == IntentType.IMAGE_REFINEMENT:
        return "Here's the refined version of the image."
    if intent == IntentType.MULTI_IMAGE_TRANSFORMATION:
        return "Here's the combined output from your images."
    return "I processed your request."


# ── Nodes ──────────────────────────────────────────────────────────────────────


async def load_context(state: VizzyState) -> dict[str, Any]:
    """Load conversation history into the state."""
    logger.debug("Node: load_context")
    builder = ContextBuilder()
    history = builder.build_context(state["conversation_id"], state["user_id"])
    return {"conversation_history": history}


async def resolve_assets(state: VizzyState) -> dict[str, Any]:
    """Resolve input and/or target asset metadata.

    Reads input_asset_ids from state (set by message service before graph entry).
    Resolves full asset metadata for each ID, enforcing user ownership.
    Does NOT download image bytes here — bytes are fetched in generation nodes.
    """
    logger.debug("Node: resolve_assets")
    resolver = AssetResolver()
    user_id = state["user_id"]
    input_ids = state.get("input_asset_ids") or []

    resolved_inputs: list[dict[str, Any]] = []
    if input_ids:
        try:
            resolved_inputs = resolver.resolve_explicit(input_ids, user_id)
            logger.debug("Resolved %d input asset(s)", len(resolved_inputs))
        except Exception as exc:
            logger.warning("Asset resolution failed: %s", exc)
            return {"error": str(exc), "resolved_input_assets": [], "resolved_target_asset": None}

    return {
        "resolved_input_assets": resolved_inputs,
        "resolved_target_asset": None,  # Refinement target resolved in refine_image node
    }


async def understand_intent(state: VizzyState) -> dict[str, Any]:
    """Classify user intent using the LLM."""
    logger.debug("Node: understand_intent")
    classifier = IntentClassifier()

    history = state.get("conversation_history", [])
    current_message = {"role": "user", "content": state["user_message_content"]}
    full_context = history + [current_message]

    result = await classifier.classify(full_context)

    # Inject the frontend-supplied asset_ids as input_asset_ids (backend trust only)
    input_asset_ids = state.get("input_asset_ids") or []
    result.input_asset_ids = input_asset_ids

    # Deterministic fallback/override:
    # If the user explicitly uploaded images, force the correct transformation intent.
    # If they did not, prevent transformation intents from routing to nodes that require inputs.
    if len(input_asset_ids) == 1:
        result.intent = IntentType.IMAGE_TRANSFORMATION
    elif len(input_asset_ids) > 1:
        result.intent = IntentType.MULTI_IMAGE_TRANSFORMATION
    elif not input_asset_ids and result.intent in (
        IntentType.IMAGE_TRANSFORMATION,
        IntentType.MULTI_IMAGE_TRANSFORMATION,
    ):
        result.intent = IntentType.IMAGE_REFINEMENT

    return {
        "intent": result.intent,
        "instruction": result.instruction,
    }


async def generate_image(state: VizzyState) -> dict[str, Any]:
    """Generate a brand-new image from a text prompt (IMAGE_GENERATION)."""
    logger.debug("Node: generate_image")
    instruction = state.get("instruction")
    if not instruction:
        return {"error": "No instruction provided for generation."}

    provider = HuggingFaceImageProvider()
    try:
        logger.info("generation_started conversation_id=%s intent=image_generation", state["conversation_id"])
        image_bytes = await provider.generate_image(instruction)
        return {
            "generated_image_bytes": image_bytes,
            "generation_type": "text_to_image",
            "parent_asset_id": None,
        }
    except Exception as exc:
        logger.error("Generation failed in node: %s", exc)
        return {
            "error": str(exc)
            if isinstance(exc, (ImageGenerationError, ImageTransformationError))
            else "Image generation failed."
        }


async def transform_image(state: VizzyState) -> dict[str, Any]:
    """Transform one uploaded image with an instruction (IMAGE_TRANSFORMATION)."""
    logger.debug("Node: transform_image")
    instruction = state.get("instruction")
    input_assets = state.get("resolved_input_assets") or []

    if not instruction:
        return {"error": "No transformation instruction provided."}
    if not input_assets:
        return {"error": "No input image provided for transformation."}

    # Download the input image bytes from storage
    storage = StorageService()
    settings = get_settings()
    image_bytes_list: list[bytes] = []

    for asset in input_assets[:1]:  # Single image for IMAGE_TRANSFORMATION
        try:
            # Determine bucket from storage_path prefix
            storage_path = asset["storage_path"]
            if storage_path.startswith(settings.input_image_bucket + "/"):
                path = storage_path[len(settings.input_image_bucket) + 1 :]
                bucket = settings.input_image_bucket
            elif storage_path.startswith(settings.generated_image_bucket + "/"):
                path = storage_path[len(settings.generated_image_bucket) + 1 :]
                bucket = settings.generated_image_bucket
            else:
                # Fallback: assume input bucket and use path as-is
                path = storage_path
                bucket = settings.input_image_bucket
            img_bytes = storage.download_file(bucket=bucket, path=path)
            image_bytes_list.append(img_bytes)
        except Exception as exc:
            logger.error("Failed to download input asset %s: %s", asset["id"], exc)
            return {"error": f"Failed to load input image: {exc}"}

    if not image_bytes_list:
        return {"error": "Could not load input image for transformation."}

    provider = HuggingFaceImageProvider()
    try:
        logger.info(
            "generation_started conversation_id=%s intent=image_transformation",
            state["conversation_id"],
        )
        image_bytes = await provider.transform_image(image_bytes_list, instruction)
        return {
            "generated_image_bytes": image_bytes,
            "generation_type": "image_transformation",
            "parent_asset_id": input_assets[0]["id"] if input_assets else None,
        }
    except Exception as exc:
        logger.error("Image transformation failed: %s", exc)
        return {
            "error": str(exc)
            if isinstance(exc, (ImageGenerationError, ImageTransformationError))
            else "Image transformation failed."
        }


async def refine_image(state: VizzyState) -> dict[str, Any]:
    """Refine the most-recently-generated image (IMAGE_REFINEMENT).

    Resolves target asset, downloads it, and runs image-to-image transformation.
    Sets parent_asset_id for lineage tracking.
    """
    logger.debug("Node: refine_image")
    instruction = state.get("instruction")
    if not instruction:
        return {"error": "No refinement instruction provided."}

    # Resolve target image
    resolver = AssetResolver()
    try:
        target_asset = resolver.resolve_target_asset(
            explicit_asset_id=None,  # LLM suggestions are ignored; use latest
            conversation_id=state["conversation_id"],
            user_id=state["user_id"],
            require=True,
        )
    except NoTargetImageError:
        logger.warning(
            "No target image found for refinement in conversation %s",
            state["conversation_id"],
        )
        return {"error": ("I couldn't find a previous image to refine. Please generate an image first or upload one.")}
    except Exception as exc:
        logger.error("Target asset resolution failed: %s", exc)
        return {"error": f"Failed to resolve target image: {exc}"}

    # Guard: resolve_target_asset returns dict|None; require=True raises before None,
    # but mypy cannot infer that from the exception contract alone.
    if target_asset is None:
        return {"error": ("I couldn't find a previous image to refine. Please generate an image first or upload one.")}

    # Download target image bytes
    storage = StorageService()
    settings = get_settings()
    try:
        storage_path = target_asset["storage_path"]
        if storage_path.startswith(settings.generated_image_bucket + "/"):
            path = storage_path[len(settings.generated_image_bucket) + 1 :]
            bucket = settings.generated_image_bucket
        elif storage_path.startswith(settings.input_image_bucket + "/"):
            path = storage_path[len(settings.input_image_bucket) + 1 :]
            bucket = settings.input_image_bucket
        else:
            path = storage_path
            bucket = settings.generated_image_bucket
        img_bytes = storage.download_file(bucket=bucket, path=path)
    except Exception as exc:
        logger.error("Failed to download target asset %s: %s", target_asset["id"], exc)
        return {"error": "Failed to load the target image for refinement."}

    # Augment instruction with context preservation hint
    full_instruction = f"Preserve the overall composition and subject matter. {instruction}"

    provider = HuggingFaceImageProvider()
    try:
        logger.info(
            "generation_started conversation_id=%s intent=image_refinement target=%s",
            state["conversation_id"],
            target_asset["id"],
        )
        image_bytes = await provider.transform_image([img_bytes], full_instruction)
        return {
            "generated_image_bytes": image_bytes,
            "generation_type": "image_refinement",
            "parent_asset_id": target_asset["id"],
            "resolved_target_asset": target_asset,
        }
    except Exception as exc:
        logger.error("Image refinement failed: %s", exc)
        return {
            "error": str(exc)
            if isinstance(exc, (ImageGenerationError, ImageTransformationError))
            else "Image refinement failed."
        }


async def transform_multiple_images(state: VizzyState) -> dict[str, Any]:
    """Combine multiple input images into one output (MULTI_IMAGE_TRANSFORMATION)."""
    logger.debug("Node: transform_multiple_images")
    instruction = state.get("instruction")
    input_assets = state.get("resolved_input_assets") or []

    if not instruction:
        return {"error": "No instruction provided for multi-image transformation."}
    if len(input_assets) < 2:
        return {
            "error": (
                f"Multi-image transformation requires at least 2 input images. Only {len(input_assets)} provided."
            )
        }

    # Download all input images
    storage = StorageService()
    settings = get_settings()
    image_bytes_list: list[bytes] = []

    for asset in input_assets:
        try:
            storage_path = asset["storage_path"]
            if storage_path.startswith(settings.input_image_bucket + "/"):
                path = storage_path[len(settings.input_image_bucket) + 1 :]
                bucket = settings.input_image_bucket
            elif storage_path.startswith(settings.generated_image_bucket + "/"):
                path = storage_path[len(settings.generated_image_bucket) + 1 :]
                bucket = settings.generated_image_bucket
            else:
                path = storage_path
                bucket = settings.input_image_bucket
            img_bytes = storage.download_file(bucket=bucket, path=path)
            image_bytes_list.append(img_bytes)
        except Exception as exc:
            logger.error("Failed to download asset %s: %s", asset["id"], exc)
            return {"error": f"Failed to load input image {asset['id']}: {exc}"}

    provider = HuggingFaceImageProvider()
    try:
        logger.info(
            "generation_started conversation_id=%s intent=multi_image_transformation num_inputs=%d",
            state["conversation_id"],
            len(image_bytes_list),
        )
        image_bytes = await provider.transform_image(image_bytes_list, instruction)
        return {
            "generated_image_bytes": image_bytes,
            "generation_type": "multi_image_transformation",
            "parent_asset_id": None,
        }
    except Exception as exc:
        logger.error("Multi-image transformation failed: %s", exc)
        return {
            "error": str(exc)
            if isinstance(exc, (ImageGenerationError, ImageTransformationError))
            else "Multi-image transformation failed."
        }


async def save_result(state: VizzyState) -> dict[str, Any]:
    """Upload generated bytes to storage and create the asset record.

    Also creates asset_inputs relationships for multi-image transformations.
    Sets parent_asset_id for lineage tracking.
    """
    logger.debug("Node: save_result")
    image_bytes = state.get("generated_image_bytes")

    if state.get("error"):
        # A generation node already recorded an error — skip saving.
        return {}

    if not image_bytes:
        logger.error("save_result reached with no generated_image_bytes and no error in state")
        return {"error": "Image generation produced no bytes."}

    settings = get_settings()
    storage = StorageService()
    asset_repo = AssetRepository()

    # Generate unique file path
    filename = f"{uuid.uuid4().hex}.png"
    path = f"{state['user_id']}/{state['conversation_id']}/{filename}"
    bucket = settings.generated_image_bucket

    try:
        logger.info(
            "save_result: uploading %d bytes to bucket=%s path=%s",
            len(image_bytes),
            bucket,
            path,
        )
        upload_result = storage.upload_file(
            bucket=bucket,
            path=path,
            data=image_bytes,
            content_type="image/png",
        )

        generation_type = state.get("generation_type") or "text_to_image"
        parent_asset_id = state.get("parent_asset_id")
        instruction = state.get("instruction") or "Unknown prompt"

        # Create the asset record
        asset = asset_repo.create_generated_asset(
            user_id=state["user_id"],
            conversation_id=state["conversation_id"],
            message_id=None,  # Linked later in save_assistant_message
            storage_path=upload_result.full_path,
            mime_type="image/png",
            prompt=instruction,
            generation_type=generation_type,
            parent_asset_id=parent_asset_id,
        )

        # Create asset_inputs relationships for multi-image transformation
        input_assets = state.get("resolved_input_assets") or []
        if input_assets:
            for input_asset in input_assets:
                try:
                    asset_repo.create_asset_input_relationship(
                        output_asset_id=asset["id"],
                        input_asset_id=input_asset["id"],
                    )
                except Exception as rel_exc:
                    logger.warning(
                        "Failed to create asset_input relationship %s→%s: %s",
                        input_asset["id"],
                        asset["id"],
                        rel_exc,
                    )

        logger.info(
            "generation_completed conversation_id=%s asset_id=%s generation_type=%s",
            state["conversation_id"],
            asset["id"],
            generation_type,
        )

        return {
            "generated_asset_id": asset["id"],
            "generated_storage_path": upload_result.full_path,
            "generated_mime_type": "image/png",
            "response_text": _generation_response_text(state.get("intent")),
        }
    except Exception as exc:
        # Log the full exception so it is visible in server logs.
        # Propagate as state error so save_assistant_message delivers the error
        # to the user rather than returning a silent 201 with generated_asset=None.
        logger.exception("Storage/Asset save failed in save_result node: %s", exc)
        return {"error": f"Failed to save generated image: {exc}"}


async def unsupported_request(state: VizzyState) -> dict[str, Any]:
    """Handle unsupported intent types."""
    logger.debug("Node: unsupported_request")
    return {
        "response_text": (
            "I can generate new images from text descriptions, transform images "
            "with editing instructions, refine previously generated images, and "
            "combine multiple images into one. Please try rephrasing your request."
        )
    }


async def save_assistant_message(state: VizzyState) -> dict[str, Any]:
    """Create the assistant message and link the generated asset."""
    logger.debug("Node: save_assistant_message")

    response_text = state.get("response_text")
    if state.get("error"):
        response_text = f"Sorry, something went wrong: {state['error']}"
    elif not response_text:
        response_text = "I processed your request."

    msg_repo = MessageRepository()
    asset_repo = AssetRepository()

    try:
        message = msg_repo.create(
            conversation_id=state["conversation_id"],
            user_id=state["user_id"],
            role="assistant",
            content=response_text,
        )

        # Link the generated asset to this message
        asset_id = state.get("generated_asset_id")
        if asset_id:
            asset_repo.update_message_id(asset_id, message["id"])

        logger.debug("Node: save_assistant_message complete, message_id=%s", message["id"])
        return {}
    except Exception as exc:
        logger.error("Saving assistant message failed: %s", exc)
        return {"error": "Failed to save assistant message."}
